### ISSUE TITLE
메달 지급 알림센터 알림 기능

### ISSUE THREAD

**Issue by wookho** [bjrambo/experience#1]
혹시 몰라 등록합니다.

저희는 경험치모듈을 순수하게 메달을 지급하는 용도로 사용해서 레벨은 따로 사이트에 적용하거나 하지 않고 있습니다.
레벨은 포인트 모듈과 연동되어 포인트에 따라 결정되는 레벨이 사이트에서 공식적으로 회원들에게 알려주고 있는 실제 레벨입니다.

모듈 관리자 페이지에 보면 
레벨업 알림
 레벨업을 했을때 알림센터를 통해 해당 회원이 알림을 받을 수 있습니다.

위 체크 항목이 있는데 저희는 저 기능을 사용하면 안되는 사이트 입니다.

혹시 저 체크가 선행되어야 메달지급 알림도 가능한 구조라면 두 설정이 분리되거나 혹은 메달지급 알림은 저 체크를 하지 않아도 알림이 전송될 수 있으면 좋겠습니다.

**Comment by bjrambo** [comment]
https://github.com/bjrambo/experience/blob/master/experience.admin.controller.php#L245

실제로 crontab 해서 들어가는 곳은 아직 알림센터 적용안햇는데 따로 알림센터기능은 분리될 예정입니다만..
