### ISSUE TITLE
crontab 사용 설명 부탁드려요.

### ISSUE THREAD

**Issue by wookho** [bjrambo/experience#2]
매월 1일 00시 05분에 메달을 새로 지급하려고 합니다.

**Comment by bjrambo** [comment]
`5 0 1 * * cd /home/~~~~~~~/modules/experience; php crontab.php > /dev/null 2>&1`

**Comment by bjrambo** [comment]
관련 내용은 구글에 잘 찾아보세요 XD

**Comment by wookho** [comment]
@bjrambo 네.  파일이 보여서 사용 가능한건지 겸 여쭤봤습니다.
