### ISSUE TITLE
브론즈 메달이 설정한 숫자보다 너무 많이 지급됩니다.

### ISSUE THREAD

**Issue by wookho** [bjrambo/experience#3]
두개의 사이트에서 모두 너무 설정한 숫자보다 많이 지급되는 현상이 발생했습니다.

**Comment by wookho** [comment]
$args->list_count = $config->medal_bronze;

메달지급 쿼리에 위 내용 추가하고 해결 되었습니다.

**Comment by bjrambo** [comment]
아 해당 부분 설정을 안햇었네요. 수정하겠습니다. 감사합니다.

**Comment by bjrambo** [comment]
Fixed https://github.com/bjrambo/experience/commit/916cb5f35ff2698c05dc49c1878ccc57e8a14b6e
