### ISSUE TITLE
1월 월간 경험치 db에 기록되지 않습니다.

### ISSUE THREAD

**Issue by wookho** [bjrambo/experience#4]
1월 1일 오늘 게시글,댓글 작성으로 포인트가 적립된 회원들 월간 경험치가 부여되지 않아 db에 12월 데이터만 있습니다.

**Comment by bjrambo** [comment]
제 개인서버에서는 정상적으로 잘 작동하는 것으로 보이고 있습니다.

실제로 활동을 해보신다음 어떻게 디비에 뜨는지 에러같은거 확인하실 수 있으신가요?

**Comment by wookho** [comment]
포인트,경험치 다 증가합니다.
그런데 모든 회원의 01월 월간 경험치 신규 생성이 안됩니다.

12월 데이터는 다 있습니디.

**Comment by bjrambo** [comment]
Fixed https://github.com/bjrambo/experience/commit/074ee18a80420a0071967e36415c521472949afe
